-- check_constraints.sql
SET @has_cc := (
  SELECT COUNT(*)
  FROM information_schema.TABLES
  WHERE TABLE_SCHEMA = 'information_schema'
    AND TABLE_NAME   = 'CHECK_CONSTRAINTS'
);

SET @sql := IF(@has_cc > 0,
  'SELECT tc.CONSTRAINT_SCHEMA, tc.TABLE_NAME, tc.CONSTRAINT_NAME, cc.CHECK_CLAUSE
     FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc
     JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
       ON cc.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
      AND cc.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
    WHERE tc.CONSTRAINT_SCHEMA NOT IN (''mysql'',''information_schema'',''performance_schema'',''sys'')',
  'SELECT NULL, NULL, NULL, NULL FROM DUAL WHERE 1=0'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

