"""Tests for orchestrator.tui.rundir: run-dir discovery, signatures, resume.

TDD unit 6 (design doc tui-phase0-design.md Sec 5.4). ``resume_decision``
gets exhaustive table coverage here (not left to a screen's pilot tests
later) because a prior pass on the design doc dropped a whole resume
branch -- this is pure logic and cheap to test exhaustively.
"""

from __future__ import annotations

import dataclasses
import json
from datetime import datetime
from pathlib import Path

import pytest

from orchestrator.tui.models import (
    ConfigDraft,
    ResumeCandidate,
    ResumeDecision,
    ResumeVerdict,
)
from orchestrator.tui.rundir import (
    ARTIFACTS_DIR,
    NO_RESUME_MODES,
    RUN_DIR_FILE,
    RUN_SIG_FILE,
    SIGNATURE_KEYS,
    STATE_FILE,
    TS_FORMAT,
    UNCONDITIONAL_RESUME_MODES,
    _MSG_FORCED,
    _MSG_INPUTS_CHANGED,
    _MSG_TWO_STEP,
    clear_pointers,
    default_ts,
    discover,
    force_new_run_from_env,
    new_run_dir,
    parse_run_dir_name,
    read_last_signature,
    read_pointer,
    resume_decision,
    run_signature,
    write_pointers,
)

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "signature"

EXPECTED_SIGNATURE_KEYS = (
    "MODE",
    "STAGED_PHASE",
    "STAGED_DUMP_DIR",
    "SRC_HOST",
    "SRC_PORT",
    "SRC_ADMIN_USER",
    "SRC_DBS_INPUT",
    "TGT_HOST",
    "TGT_PORT",
    "TGT_ADMIN_USER",
    "TGT_SSH_HOST",
    "TGT_SSH_USER",
    "MIGRATE_APP_USERS",
    "ANALYZE_TARGET",
    "INSTALL_TARGET_MARIADB",
    "TARGET_INSTALL_OS",
    "TARGET_MARIADB_VERSION",
    "REPL_USER",
    "INPLACE_BACKUP_DIR",
    "INPLACE_EXECUTE",
    "INPLACE_TARGET_OS",
    "INPLACE_MARIADB_VERSION",
    "REPLACE_TARGET_OS",
    "REPLACE_MARIADB_VERSION",
    "REPLACE_DELETE_OLD_MYSQL_DATA",
)


class TestRunSignature:
    def test_signature_keys_count_and_order(self):
        assert len(SIGNATURE_KEYS) == 25
        assert SIGNATURE_KEYS == EXPECTED_SIGNATURE_KEYS

    def test_golden_fixture(self):
        fixture_text = (FIXTURES_DIR / "one_step_wizard_v1.sig").read_text()
        fields = json.loads((FIXTURES_DIR / "one_step_wizard_v1.json").read_text())
        fields = {k: v for k, v in fields.items() if k != "_generated_by"}
        mode = fields.pop("MODE")
        draft = ConfigDraft(mode=mode, **fields)

        result = run_signature(draft)

        assert result == fixture_text
        assert result.count("\n") == 24

    def test_signature_survives_config_load_round_trip(self):
        """A config loaded via configio.yaml_to_draft must still produce a
        wizard-parity signature -- this is the regression test for review
        findings F2/F3: yaml_to_draft's fallback defaults for
        INSTALL_TARGET_MARIADB and SRC_DBS_INPUT previously produced "" for
        any config missing those keys (which config/migration.yaml.example
        does), breaking signature parity for every non-binlog/replace_slave
        mode. The fixture signature was generated by sourcing and invoking
        the real mariadb-migrator run_signature() bash function directly
        with config/migration.yaml.example's exact field values.
        """
        from orchestrator.tui.configio import yaml_to_draft

        example_path = (
            Path(__file__).parent.parent.parent.parent
            / "config"
            / "migration.yaml.example"
        )
        draft = yaml_to_draft(example_path.read_text())

        fixture_text = (
            FIXTURES_DIR / "example_config_wizard_v1.sig"
        ).read_text()
        assert run_signature(draft) == fixture_text

    def test_default_install_target_mariadb_parity(self):
        draft = ConfigDraft(mode="one_step")
        lines = run_signature(draft).split("\n")
        assert "INSTALL_TARGET_MARIADB=0" in lines
        assert "TARGET_INSTALL_OS=" in lines
        assert "TARGET_MARIADB_VERSION=" in lines

    def test_no_password_in_signature(self):
        sentinel = "SENTINEL_SECRET_VALUE"
        password_fields = [
            f.name
            for f in dataclasses.fields(ConfigDraft)
            if "PASS" in f.name or f.name == "APP_USER_DEFAULT_PASSWORD"
        ]
        assert password_fields, "expected at least one password-like field"
        kwargs = {name: sentinel for name in password_fields}
        draft = ConfigDraft(mode="one_step", **kwargs)

        sig = run_signature(draft)

        assert sentinel not in sig

    def test_src_dbs_input_raw_not_split(self):
        draft = ConfigDraft(
            mode="one_step",
            SRC_DB="db1",
            SRC_DBS="db2",
            SRC_DBS_INPUT="db1, db2",
        )
        lines = run_signature(draft).split("\n")
        assert "SRC_DBS_INPUT=db1, db2" in lines

    @pytest.mark.parametrize(
        "staged_phase_field, expected_line",
        [
            ("dump_only", "STAGED_PHASE=dump_only"),
            ("", "STAGED_PHASE="),
        ],
        ids=["set", "empty"],
    )
    def test_staged_phase_resolution(self, staged_phase_field, expected_line):
        draft = ConfigDraft(mode="staged", STAGED_PHASE=staged_phase_field)
        lines = run_signature(draft).split("\n")
        assert expected_line in lines

    def test_empty_field_renders_bare_key(self):
        draft = ConfigDraft(mode="one_step")
        lines = run_signature(draft).split("\n")
        assert "REPL_USER=" in lines

    def test_staged_dump_dir_is_real_configdraft_field(self):
        assert "STAGED_DUMP_DIR" in {f.name for f in dataclasses.fields(ConfigDraft)}


class TestParseRunDirName:
    @pytest.mark.parametrize(
        "mode",
        ["one_step", "two_step", "staged", "binlog", "inplace", "replace_slave"],
    )
    def test_valid_names(self, mode):
        name = f"run_{mode}_20260805_141530"
        assert parse_run_dir_name(name) == (mode, "20260805_141530")

    @pytest.mark.parametrize(
        "name",
        [
            "run_binlog",
            "assess_20260805_141530",
            "run_binlog_2026085_141530",
            "run_binlog_20260805_14153",
            "",
        ],
        ids=["no-ts", "wrong-prefix", "7-digit-date", "5-digit-time", "empty"],
    )
    def test_invalid_names(self, name):
        assert parse_run_dir_name(name) is None


class TestNewRunDirAndDefaultTs:
    def test_new_run_dir(self):
        assert new_run_dir("replace_slave", "20260805_141530") == Path(
            "artifacts/run_replace_slave_20260805_141530"
        )

    def test_new_run_dir_is_not_absolute(self):
        assert not new_run_dir("one_step", "20260805_141530").is_absolute()

    @pytest.mark.parametrize(
        "mode",
        ["one_step", "two_step", "staged", "binlog", "inplace", "replace_slave"],
    )
    def test_round_trip_through_parse(self, mode):
        ts = "20260805_141530"
        run_dir = new_run_dir(mode, ts)
        assert parse_run_dir_name(run_dir.name) == (mode, ts)

    def test_default_ts(self):
        assert default_ts(datetime(2026, 8, 5, 14, 15, 30)) == "20260805_141530"


class TestPointerHelpers:
    def test_read_pointer_missing(self, tmp_path):
        assert read_pointer(tmp_path) == ""

    def test_read_pointer_only_newline(self, tmp_path):
        (tmp_path / RUN_DIR_FILE).write_text("\n")
        assert read_pointer(tmp_path) == ""

    def test_read_pointer_empty_file(self, tmp_path):
        (tmp_path / RUN_DIR_FILE).write_text("")
        assert read_pointer(tmp_path) == ""

    def test_read_pointer_strips_all_newlines(self, tmp_path):
        (tmp_path / RUN_DIR_FILE).write_text("artifacts/a\nartifacts/b\n")
        assert read_pointer(tmp_path) == "artifacts/aartifacts/b"

    def test_read_last_signature_missing(self, tmp_path):
        assert read_last_signature(tmp_path) == ""

    def test_read_last_signature_empty_file(self, tmp_path):
        (tmp_path / RUN_SIG_FILE).write_text("")
        assert read_last_signature(tmp_path) == ""

    def test_read_last_signature_strips_trailing_only(self, tmp_path):
        (tmp_path / RUN_SIG_FILE).write_text("MODE=one_step\n\n")
        assert read_last_signature(tmp_path) == "MODE=one_step"

    def test_read_last_signature_preserves_interior_newlines(self, tmp_path):
        (tmp_path / RUN_SIG_FILE).write_text("a\nb\n")
        assert read_last_signature(tmp_path) == "a\nb"

    def test_write_pointers_run_pointer_has_one_trailing_newline(self, tmp_path):
        write_pointers(
            tmp_path, Path("artifacts/run_one_step_20260805_141530"), "MODE=one_step"
        )
        raw = (tmp_path / RUN_DIR_FILE).read_bytes()
        assert raw.endswith(b"\n")
        assert raw.count(b"\n") == 1

    def test_write_pointers_sig_has_no_trailing_newline(self, tmp_path):
        write_pointers(
            tmp_path, Path("artifacts/run_one_step_20260805_141530"), "MODE=one_step"
        )
        raw = (tmp_path / RUN_SIG_FILE).read_bytes()
        assert not raw.endswith(b"\n")

    def test_write_pointers_round_trips(self, tmp_path):
        run_dir = Path("artifacts/run_one_step_20260805_141530")
        sig = "MODE=one_step\nSTAGED_PHASE="
        write_pointers(tmp_path, run_dir, sig)
        assert read_pointer(tmp_path) == str(run_dir)
        assert read_last_signature(tmp_path) == sig

    def test_clear_pointers_idempotent_on_empty_dir(self, tmp_path):
        clear_pointers(tmp_path)  # must not raise

    def test_clear_pointers_removes_both_files(self, tmp_path):
        (tmp_path / RUN_DIR_FILE).write_text("x\n")
        (tmp_path / RUN_SIG_FILE).write_text("y")
        clear_pointers(tmp_path)
        assert not (tmp_path / RUN_DIR_FILE).exists()
        assert not (tmp_path / RUN_SIG_FILE).exists()


class TestForceNewRunFromEnv:
    @pytest.mark.parametrize(
        "env, expected",
        [
            ({}, False),
            ({"FORCE_NEW_RUN": ""}, False),
            ({"FORCE_NEW_RUN": "0"}, False),
            ({"FORCE_NEW_RUN": "true"}, False),
            ({"FORCE_NEW_RUN": "yes"}, False),
            ({"FORCE_NEW_RUN": "TRUE"}, False),
            ({"FORCE_NEW_RUN": "1"}, True),
            ({"FORCE_NEW_RUN": "11"}, False),
        ],
    )
    def test_cases(self, env, expected):
        assert force_new_run_from_env(env) is expected


class TestDiscover:
    def test_no_pointer_file(self, tmp_path):
        assert discover(tmp_path) is None

    def test_empty_pointer(self, tmp_path):
        (tmp_path / RUN_DIR_FILE).write_text("")
        assert discover(tmp_path) is None

    def test_pointer_to_nonexistent_path(self, tmp_path):
        (tmp_path / RUN_DIR_FILE).write_text(
            "artifacts/run_one_step_20260805_141530\n"
        )
        assert discover(tmp_path) is None

    def test_pointer_to_file_not_directory(self, tmp_path):
        target_dir = tmp_path / ARTIFACTS_DIR
        target_dir.mkdir()
        (target_dir / "not_a_dir").write_text("x")
        (tmp_path / RUN_DIR_FILE).write_text("artifacts/not_a_dir\n")
        assert discover(tmp_path) is None

    def test_directory_exists_no_state_json(self, tmp_path):
        run_dir = tmp_path / ARTIFACTS_DIR / "run_one_step_20260805_141530"
        run_dir.mkdir(parents=True)
        (tmp_path / RUN_DIR_FILE).write_text(
            "artifacts/run_one_step_20260805_141530\n"
        )
        assert discover(tmp_path) is None

    def test_state_json_is_a_directory(self, tmp_path):
        run_dir = tmp_path / ARTIFACTS_DIR / "run_one_step_20260805_141530"
        (run_dir / STATE_FILE).mkdir(parents=True)
        (tmp_path / RUN_DIR_FILE).write_text(
            "artifacts/run_one_step_20260805_141530\n"
        )
        assert discover(tmp_path) is None

    @staticmethod
    def _seed_valid_run(tmp_path, *, dir_name="run_one_step_20260805_141530", with_sig=False):
        raw = f"{ARTIFACTS_DIR}/{dir_name}"
        run_dir = tmp_path / ARTIFACTS_DIR / dir_name
        run_dir.mkdir(parents=True)
        (run_dir / STATE_FILE).write_text("{}")
        (tmp_path / RUN_DIR_FILE).write_text(raw + "\n")
        if with_sig:
            (tmp_path / RUN_SIG_FILE).write_text("MODE=one_step")
        return raw, run_dir

    def test_valid_candidate_no_signature_file(self, tmp_path):
        raw, run_dir = self._seed_valid_run(tmp_path)

        candidate = discover(tmp_path)

        assert candidate is not None
        assert candidate.raw_pointer == raw
        assert candidate.run_dir == run_dir
        assert candidate.dir_mode == "one_step"
        assert candidate.dir_ts == "20260805_141530"
        assert candidate.last_sig == ""
        assert isinstance(candidate.state_mtime, float)

    def test_valid_candidate_with_signature_file(self, tmp_path):
        self._seed_valid_run(tmp_path, with_sig=True)

        candidate = discover(tmp_path)

        assert candidate.last_sig == "MODE=one_step"

    def test_unparseable_dir_name_still_returns_candidate(self, tmp_path):
        self._seed_valid_run(tmp_path, dir_name="not_matching_pattern")

        candidate = discover(tmp_path)

        assert candidate is not None
        assert candidate.dir_mode is None
        assert candidate.dir_ts is None

    def test_discover_never_mutates_tree(self, tmp_path):
        self._seed_valid_run(tmp_path)
        before = sorted(
            p.relative_to(tmp_path).as_posix() for p in tmp_path.rglob("*")
        )

        discover(tmp_path)

        after = sorted(
            p.relative_to(tmp_path).as_posix() for p in tmp_path.rglob("*")
        )
        assert before == after


def _make_candidate(*, dir_mode, last_sig):
    return ResumeCandidate(
        raw_pointer="artifacts/run_x_20260805_141530",
        run_dir=Path("artifacts/run_x_20260805_141530"),
        dir_mode=dir_mode,
        dir_ts="20260805_141530",
        last_sig=last_sig,
        state_mtime=0.0,
    )


CURRENT_SIG = "MODE=one_step\nSTAGED_PHASE="
OTHER_SIG = "MODE=one_step\nSTAGED_PHASE=dump_only"

# (mode, has_candidate, candidate_last_sig, force_new_run, expected_verdict)
RESUME_TABLE = [
    ("binlog", True, OTHER_SIG, False, ResumeVerdict.RESUME_UNCONDITIONAL),
    ("binlog", True, "", False, ResumeVerdict.RESUME_UNCONDITIONAL),
    ("replace_slave", True, OTHER_SIG, False, ResumeVerdict.RESUME_UNCONDITIONAL),
    ("binlog", True, CURRENT_SIG, True, ResumeVerdict.FRESH_FORCED),
    ("binlog", False, None, False, ResumeVerdict.FRESH_NO_CANDIDATE),
    ("one_step", True, CURRENT_SIG, False, ResumeVerdict.RESUME_SIGNATURE_MATCH),
    ("staged", True, CURRENT_SIG, False, ResumeVerdict.RESUME_SIGNATURE_MATCH),
    ("inplace", True, CURRENT_SIG, False, ResumeVerdict.RESUME_SIGNATURE_MATCH),
    ("one_step", True, OTHER_SIG, False, ResumeVerdict.FRESH_INPUTS_CHANGED),
    ("one_step", True, "", False, ResumeVerdict.FRESH_INPUTS_CHANGED),
    ("one_step", True, CURRENT_SIG, True, ResumeVerdict.FRESH_FORCED),
    ("two_step", True, CURRENT_SIG, False, ResumeVerdict.FRESH_TWO_STEP),
    ("two_step", True, OTHER_SIG, False, ResumeVerdict.FRESH_TWO_STEP),
    ("two_step", True, CURRENT_SIG, True, ResumeVerdict.FRESH_FORCED),
    ("one_step", False, None, True, ResumeVerdict.FRESH_NO_CANDIDATE),
]

RESUME_TABLE_IDS = [
    "binlog-differ-unconditional",
    "binlog-empty-lastsig-unconditional",
    "replace_slave-differ-unconditional",
    "binlog-forced-match-still-forced",
    "binlog-no-candidate",
    "one_step-match-resumes",
    "staged-match-resumes",
    "inplace-match-resumes",
    "one_step-differ-fresh",
    "one_step-empty-lastsig-fresh",
    "one_step-forced-match-fresh",
    "two_step-match-still-fresh",
    "two_step-differ-fresh",
    "two_step-forced-fresh",
    "no-candidate-wins-over-force",
]


class TestResumeDecision:
    @pytest.mark.parametrize(
        "mode, has_candidate, last_sig, force, expected",
        RESUME_TABLE,
        ids=RESUME_TABLE_IDS,
    )
    def test_table(self, mode, has_candidate, last_sig, force, expected):
        candidate = (
            _make_candidate(dir_mode=mode, last_sig=last_sig)
            if has_candidate
            else None
        )
        decision = resume_decision(
            candidate, mode=mode, current_sig=CURRENT_SIG, force_new_run=force
        )
        assert decision.verdict == expected

    def test_no_candidate_message_empty(self):
        decision = resume_decision(
            None, mode="one_step", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.message == ""

    def test_resume_unconditional_message_empty(self):
        candidate = _make_candidate(dir_mode="binlog", last_sig=OTHER_SIG)
        decision = resume_decision(
            candidate, mode="binlog", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.message == ""

    def test_resume_signature_match_message_empty(self):
        candidate = _make_candidate(dir_mode="one_step", last_sig=CURRENT_SIG)
        decision = resume_decision(
            candidate, mode="one_step", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.message == ""

    @pytest.mark.parametrize(
        "mode, force",
        [
            ("one_step", True),
            ("two_step", False),
            ("one_step", False),
        ],
        ids=["forced", "two_step", "inputs_changed"],
    )
    def test_fresh_messages_non_empty(self, mode, force):
        candidate = _make_candidate(dir_mode=mode, last_sig=OTHER_SIG)
        decision = resume_decision(
            candidate, mode=mode, current_sig=CURRENT_SIG, force_new_run=force
        )
        assert decision.message != ""

    def test_msg_two_step_contains_newline(self):
        assert "\n" in _MSG_TWO_STEP

    def test_can_resume_true_only_for_resume_verdicts(self):
        for verdict in ResumeVerdict:
            decision = ResumeDecision(
                verdict=verdict, candidate=None, message="", mode_mismatch=False
            )
            expected = verdict in (
                ResumeVerdict.RESUME_UNCONDITIONAL,
                ResumeVerdict.RESUME_SIGNATURE_MATCH,
            )
            assert decision.can_resume is expected

    def test_mode_mismatch_true_and_verdict_still_unconditional(self):
        candidate = _make_candidate(dir_mode="one_step", last_sig="")
        decision = resume_decision(
            candidate, mode="binlog", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.mode_mismatch is True
        assert decision.verdict == ResumeVerdict.RESUME_UNCONDITIONAL

    def test_mode_mismatch_false_when_dir_mode_matches(self):
        candidate = _make_candidate(dir_mode="binlog", last_sig="")
        decision = resume_decision(
            candidate, mode="binlog", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.mode_mismatch is False

    def test_mode_mismatch_false_when_dir_mode_none(self):
        candidate = _make_candidate(dir_mode=None, last_sig="")
        decision = resume_decision(
            candidate, mode="binlog", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.mode_mismatch is False

    def test_mode_mismatch_false_when_candidate_none(self):
        decision = resume_decision(
            None, mode="binlog", current_sig=CURRENT_SIG, force_new_run=False
        )
        assert decision.mode_mismatch is False
